project:
  type: website

website:
  title: "docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cad.qmd
        text: CAD

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



